const colors = {
  light: {
    text: "#0A1128",
    tint: "#F59E0B",
    background: "#F8FAFC",
    foreground: "#0A1128",
    card: "#FFFFFF",
    cardForeground: "#0A1128",
    primary: "#0A1128",
    primaryForeground: "#FFFFFF",
    secondary: "#E2E8F0",
    secondaryForeground: "#0F172A",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#F59E0B",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#E2E8F0",
  },
  dark: {
    text: "#F8FAFC",
    tint: "#F59E0B",
    background: "#020617",
    foreground: "#F8FAFC",
    card: "#0F172A",
    cardForeground: "#F8FAFC",
    primary: "#0A1128",
    primaryForeground: "#FFFFFF",
    secondary: "#1E293B",
    secondaryForeground: "#F8FAFC",
    muted: "#0F172A",
    mutedForeground: "#94A3B8",
    accent: "#F59E0B",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E293B",
    input: "#1E293B",
  },
  radius: 12,
};

export default colors;
